### ISSUE TITLE
Reorganization of the repo using Maven modules

### ISSUE THREAD

**Issue by hartig** [LiUSemWeb/HeFQUIN#356]
To begin with, we want the following modules.
* hefquin-base
  * This is for basic data structures, and is the root in terms of dependencies (i.e., it depends on none of the other modules).
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/engine/data/
    * ./src/test/java/se/liu/ida/hefquin/engine/data/
    * ./src/main/java/se/liu/ida/hefquin/engine/query/
    * (we can talk later about adapting the Java package names, `se.liu.ida.hefquin.engine.*` -> `se.liu.ida.hefquin.base.*`)
    * ./src/main/java/se/liu/ida/hefquin/jenaext/
    * ./src/test/java/se/liu/ida/hefquin/jenaext/
* hefquin-engine
  * the code for the actual query engine
  * depends on pgconnector, graphqlconnector, and base
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/engine/ that is not moved to base
    * ./src/test/java/se/liu/ida/hefquin/engine/ that is not moved to base
    * ./src/main/java/se/liu/ida/hefquin/jenaintegration/
    * ./src/main/java/se/liu/ida/hefquin/vocabulary/ (we may split this up later, or move somewhere else)
* hefquin-pgconnector
  * the code for querying PG data sources (only Neo4j at the moment)
  * might depend on base
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/
    * ./src/test/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/
* hefquin-graphqlconnector
  * the code for querying GraphQL servers
  * might depend on base
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/
    * ./src/test/java/se/liu/ida/hefquin/engine/wrappers/graphqlwrapper/
* hefquin-cli
  * the code and the scripts for the CLI
  * depends on engine
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/cli  (but later, some of these files should actually be moved to pgconnector!)
* hefquin-docker
  * not actually a Maven module (?), contains the Docker-related files
* hefquin-service
  * the code for the Web service
  * depends on engine
  * Files to move into this module is everything under
    * ./src/main/java/se/liu/ida/hefquin/service/
    * ./src/test/java/se/liu/ida/hefquin/service/

**Comment by hartig** [comment]
The work on this can start once the following four PRs are merged (or decided to be dropped): #221 #288 #352 #354

**Comment by huanyu-li** [comment]
> /cc @huanyu-li just for your information, Robin and I are planning to reorganize the repo

OK, I see.

**Comment by hartig** [comment]
All of [the aforementioned PRs](https://github.com/LiUSemWeb/HeFQUIN/issues/356#issuecomment-2307405095) have been taken care of.

@keski the repo is ready for you to get started working on this task.

**Comment by keski** [comment]
I've been working on the restructuring and just thought I'd share the progress so far.

I've created the overall structure for the all proposed sub-modules and specified their dependencies, and I have successfully moved the code for hefquin-cli, hefquin-service and hefquin-base. However, when I attempted to move files into hefquin-pgconnector, hefquin-graphqlconnector and hefquin-engine there turned out to be some inter-dependencies between the modules that I could not resolve without some further restructuring. I've therefore left these files in hefquin-base for now.

Currently, I'm working on on a bug to resolve a missing transitive dependency in the jar-file generated for the the hefquin-service. After that I can push the branch and we can start manually moving files to their appropriate locations and discuss further steps.

@hartig

**Comment by keski** [comment]
I've now pushed the reorganized project to the branch [restructure](https://github.com/LiUSemWeb/HeFQUIN/tree/restructure).

Each module is associated with its own `pom.xml` file. This file can be used to include specific dependencies (including other modules) and to customize its build configuration. Uber jars/wars that include all dependencies are currently only built for `hefquin-cli` and `hefquin-war`. Note that building uber jars for all submodules indiscriminately can drastically increase the size of the resulting jars/wars for modules that import other modules.

**Build**
```bash
$ mvn clean package
```

**Run `hefquin-cli`**
```bash
$ java -cp hefquin-cli/target/hefquin-cli-0.0.4-SNAPSHOT.jar \
    se.liu.ida.hefquin.cli.RunQueryWithoutSrcSel \
    -fd ExampleFederation.ttl \
    --query ExampleQuery.rq
```

**Run `hefquin-service`**
```bash
$ java -cp hefquin-service/target/hefquin-service-0.0.4-SNAPSHOT.jar \
    se.liu.ida.hefquin.service.HeFQUINServer                  
```

**Comment by hartig** [comment]
I have tried to compile the branch and run the commands as you describe, which works without problems :-)

> Uber jars/wars that include all dependencies are currently only built for hefquin-cli and hefquin-war.

That's fine.

What are the next steps now that still need to be done?
* Moving code from hefquin-base to hefquin-pgconnector, hefquin-graphqlconnector, and hefquin-engine? Do you want me to do this?
* Putting the shell scripts into hefquin-cli, or do you see this as a separate thing that can be done later?
* Anything else?

**Comment by keski** [comment]
> Moving code from hefquin-base to hefquin-pgconnector, hefquin-graphqlconnector, and hefquin-engine? Do you want me to do this?

I've moved the code to `hefquin-pgconnector` and `hefquin-graphqlconnector` (`EngineTestBase.java` just had to be copied to as part of the tests). If you could have a go at moving things into `hefquin-engine` that would be great! (But I don't think it's trivial so we could also consider skipping at least some of it and create separate issues for it).

>  Putting the shell scripts into hefquin-cli, or do you see this as a separate thing that can be done later?

I think we should probably prioritize merging into `main`, I can work on the scripts to be added to `hefquin-cli` separately.

> Anything else?

No, I think that's it for now.

**Comment by hartig** [comment]
> I've moved the code to `hefquin-pgconnector` and `hefquin-graphqlconnector`

Did you really _move_ the code or just copy? The complete `{....}/wrappers/` directory (with all its content) still exists in `hefquin-base` -- see: https://github.com/LiUSemWeb/HeFQUIN/tree/restructure/hefquin-base/src/main/java/se/liu/ida/hefquin/engine/wrappers

> (`EngineTestBase.java` just had to be copied to as part of the tests).

I see that this one may cause problems when moving things from `hefquin-base` to `hefquin-engine`. I will look into splitting it up.

> If you could have a go at moving things into hefquin-engine that would be great! (But I don't think it's trivial so we could also consider skipping at least some of it and create separate issues for it).

Okay, I will take a look at it.

> > Putting the shell scripts into hefquin-cli, or do you see this as a separate thing that can be done later?
>
> I think we should probably prioritize merging into `main`, I can work on the scripts to be added to `hefquin-cli` separately.

Okay.

**Comment by keski** [comment]
I moved `dbpedia/` into `hefquin-base` because in the file `FederationDescriptionReaderTest` there is a reference to the directory from `sparqlFMWithTwoEndpoints` (`dbpedia/vocabularyMappings.nt`) and the `RDFDataMgr.loadModel` expects to read the relative address from the module root.

**Comment by hartig** [comment]
Okay. Then let's keep it there for the moment. I have created #357 as a reminder to take care of this later.

**Comment by hartig** [comment]
What about my very first question in [my first comment from today](https://github.com/LiUSemWeb/HeFQUIN/issues/356#issuecomment-2316858117)?

**Comment by hartig** [comment]
I have managed to slightly change the test code in both `hefquin-pgconnector` and `hefquin-graphqlconnector` to be able to remove again the `EngineTestBase.java` files that you had copied into these modules (commit https://github.com/LiUSemWeb/HeFQUIN/commit/ef120fbd5181cef2b38396e7d437a353663b351c).

I see, however, that the `main` code in both of these modules has a bunch of dependencies on classes in the `se.liu.ida.hefquin.engine.federation` package and its sub-packages. This makes it currently impossible to move these packages into `hefquin-engine`. In https://github.com/LiUSemWeb/HeFQUIN-PGConnector I had already reorganized the PG connector code to get rid of these dependencies. I would carry over these changes to `hefquin-pgconnector` now, and then also use the same approach for `hefquin-graphqlconnector`. However, I agree now that this is something that is better done in a separate PR, after merging this one here.

So, I think, all that remains for the moment is an answer to my other question.

**Comment by hartig** [comment]
Oh wow! Now that is getting complicated, because there should indeed be dependencies on `hefquin-pgconnector` and `hefquin-graphqlconnector` in `hefquin-engine`, but moving the code from `hefquin-base` to `hefquin-engine` (in order to have these dependencies satisfied) will break the dependencies that `hefquin-pgconnector` and `hefquin-graphqlconnector` currently have on this code :-(
I don't want to merge the branch with two copies of the code for the connectors. So, I will have to resolve these issues already now. I will look into it.

**Comment by hartig** [comment]
Quick update: I have been working the whole day on this. I have managed to disentangle the dependencies for the PG connector, but the GraphQL-related code is quite a mess: lots of dependencies back and forth between the `...engine.federation..` packages (to be moved to the `hefquin-engine` module) and the `...wrappers.graphqlwrapper...` packages (to be moved to the `hefquin-graphqlconnector` module). I will continue with this tomorrow.

**Comment by hartig** [comment]
Success!!

I am done with disentangling the dependencies and now each Java file is in the right module. Everything compiles, the tests run without issues, and I can open the whole project in Eclipse (I had to do a fresh import of the Maven project in Eclipse).

@keski please check that it works for you as well.

In the meantime, I will create a PR.

**Comment by hartig** [comment]
@keski After creating the PR (see #358), I have cleaned up the code more, renamed some of the Java packages, copied over the improvements to the PG Connector code that I had already done in https://github.com/LiUSemWeb/HeFQUIN-PGConnector, and added some basic README files into the root directories of the various code modules. With this, I would consider the reorganization of the repo done and the PR ready to be merged. Yet, I will wait with merging until you had a chance to confirm that everything works on your end as well.

**Comment by keski** [comment]
@hartig, working fine on my side. Great work!

**Comment by hartig** [comment]
> working fine on my side.

Thanks for confirming!

> Great work!

Same :-)

**Comment by hartig** [comment]
I have merged the PR that implements the reorganization of the repo using Maven modules, which means this issue can be closed now.

@huanyu-li Since the repo has changed completely in terms of how it is set up using Maven, you may have to import it from scratch into your IDE (after doing a `git pull`, of course)
